FROM gitpod/workspace-full:latest

RUN sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https && \
    curl -sf 'https://dl.cloudsmith.io/public/caddy/xcaddy/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-xcaddy-archive-keyring.gpg && \
    curl -sf 'https://dl.cloudsmith.io/public/caddy/xcaddy/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-xcaddy.list && \
    sudo apt update && \
    sudo apt install xcaddy